### ISSUE TITLE
onActivityResultComplete is undefined

### ISSUE THREAD

**Issue by ghost** [dmitry-blackwave/adyen-react-native#1]
Hi Dmitry,
Please advised on how to implement the function:

Adyen.onActivityResultComplete((payload) => {
  // Handle payload.
});

as I get an undefined error when using it,

> undefined is not a function (evaluating '_adyenReactNative.default.onActivityResultComplete').

an example would be much appreciated.

Thanks

**Comment by dmitry-blackwave** [comment]
Hey! You need to use onPaymentResult instead.
